# Generated by Django 4.2.1 on 2023-05-30 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0003_income"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixedcosts",
            options={"verbose_name_plural": "Fixed Costs"},
        ),
        migrations.AlterModelOptions(
            name="income",
            options={"verbose_name_plural": "Income"},
        ),
        migrations.AlterModelOptions(
            name="variablecosts",
            options={"verbose_name_plural": "Variable Costs"},
        ),
    ]
