# Generated by Django 4.2.1 on 2023-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedcosts",
            name="notes",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="variablecosts",
            name="notes",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
