# Generated by Django 4.2.2 on 2023-06-10 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_alter_fixedcosts_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcosts',
            options={'ordering': ['-sume'], 'verbose_name_plural': 'Fixed Costs'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date'], 'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='variablecosts',
            options={'ordering': ['date'], 'verbose_name_plural': 'Variable Costs'},
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='variablecosts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
